POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJydW5vIiwiaWQiOiI2NWRjMTVhN2FlMDMwMWQyNTI5MWNiZjIiLCJpYXQiOjE3MDg5NzYyNTR9.usCChaTI1jPDmYFcWQ2-xrPB2gFRl63vgJV1qm8UQ9s

{
  "title": "cool blog",
  "author": "bruno",
  "url": "http://coolblog.com"
}